# Name of the workflow
name: mcmc-run

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch, as well as 1200 every day
on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
#  release:
#    types: [ published ]
#  schedule:
#    - cron:  '00 10 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Important: ubuntu-latest is not set up properly for R, so use macOS
jobs:
#  mcmc-run1:
#    runs-on: macos-latest
#    steps:
#      - name: Set up Homebrew
#        id: set-up-homebrew
#        uses: Homebrew/actions/setup-homebrew@master
#        
#      - name: Checkout repos
#        uses: actions/checkout@v2
#        with:
#          ref: master
#
#      - name: Setup R
#        uses: r-lib/actions/setup-r@v1
#
#      - name: Install dependencies
#        run: |
#          Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
#          options(install.packages.check.source = "no")
#          pkgs <- c("devtools", "dplyr", "reshape2", "ggplot2", "cowplot", "scales", "here", "deSolve", "BayesianTools", "openxlsx")
#          install.packages(pkgs, repos = "https://cloud.r-project.org/")
#        shell: Rscript {0}
# 
#      - name: Run MCMC first set
#        run: |
#          source(here::here("Fitting", "new_fitting_dens.R"))
#        shell: Rscript {0}
#
#      - name: Commit and push files
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git pull
#          git add Fitting
#          git commit -m "New MCMC run dens"
#          git push
#
#  mcmc-run2:
#    runs-on: macos-latest
#    steps:    
#      - name: Set up Homebrew
#        id: set-up-homebrew
#        uses: Homebrew/actions/setup-homebrew@master
#        
#      - name: Checkout repos
#        uses: actions/checkout@v2
#        with:
#          ref: master
#
#      - name: Setup R
#        uses: r-lib/actions/setup-r@v1
#
#      - name: Install dependencies
#        run: |
#          Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
#          options(install.packages.check.source = "no")
#          pkgs <- c("devtools", "dplyr", "reshape2", "ggplot2", "cowplot", "scales", "here", "deSolve", "BayesianTools", "openxlsx")
#          install.packages(pkgs, repos = "https://cloud.r-project.org/")
#        shell: Rscript {0}
# 
#      - name: Run MCMC first set
#        run: |
#          source(here::here("Fitting", "new_fitting_pow.R"))
#        shell: Rscript {0}
#
#      - name: Commit and push files
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git pull
#          git add Fitting
#          git commit -m "New MCMC run pow"
#          git push 


  mcmc-run3:
    runs-on: macos-latest
    steps:    
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        
      - name: Checkout repos
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
          options(install.packages.check.source = "no")
          pkgs <- c("devtools", "dplyr", "reshape2", "ggplot2", "cowplot", "scales", "here", "deSolve", "BayesianTools", "openxlsx")
          install.packages(pkgs, repos = "https://cloud.r-project.org/")
        shell: Rscript {0}
 
      - name: Run MCMC first set
        run: |
          source(here::here("Fitting", "new_fitting_hill.R"))
        shell: Rscript {0}

      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Fitting
          git commit -m "New MCMC run hill"
          git push 
