# Name of the workflow
name: test-fit

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch, as well as 1200 every day
on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
#  release:
#    types: [ published ]
#  schedule:
#    - cron:  '00 10 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Important: ubuntu-latest is not set up properly for R, so use macOS
jobs:
  test-fit-103:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        
      - name: Checkout repos
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
          options(install.packages.check.source = "no")
          pkgs <- c("devtools", "coda", "dplyr", "reshape2", "ggplot2", "cowplot", "scales", "here")
          install.packages(pkgs, repos = "https://cloud.r-project.org/")
          devtools::install_github("sbfnk/fitR")
        shell: Rscript {0}
 
      - name: Test fitted params
        run: |
          source(here::here("Fitting", "test_fitted_params_103.R"))
        shell: Rscript {0}

      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Fitting
          git commit -m "Test fitted params 103"
          git push
          
  test-fit-105:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        
      - name: Checkout repos
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "true")
          options(install.packages.check.source = "no")
          pkgs <- c("devtools", "coda", "dplyr", "reshape2", "ggplot2", "cowplot", "scales", "here")
          install.packages(pkgs, repos = "https://cloud.r-project.org/")
          devtools::install_github("sbfnk/fitR")
        shell: Rscript {0}
 
      - name: Run MCMC first set
        run: |
          source(here::here("Fitting", "test_fitted_params_105.R"))
        shell: Rscript {0}

      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Fitting
          git commit -m "Test fitted params 105"
          git push
